domain_path: /home/alt164/repositories/hdmi_example/vitis_workspace/platform/export/platform/sw/standalone_psu_cortexa53_0
app_src_dir: /opt/fpga/amd/2025.2/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
